"""
Streamlit web app for the workout suggestor.

Same RAG pattern as the CLI version (workout.py): filter a real
exercise database by your requirements, then ask a local LLM (via
Ollama) to turn the filtered list into a structured plan -- just with
a proper web UI instead of typing answers into a terminal.

Prerequisites:
    ollama serve                 (or the Ollama app running)
    ollama pull llama3.2:3b      (or: ollama pull gemma2:2b)
    pip3 install streamlit requests --break-system-packages

Run with:
    streamlit run app.py
"""

import json

import pandas as pd
import requests
import streamlit as st

from retriever import WorkoutRetriever, GOAL_TO_CATEGORIES

OLLAMA_URL = "http://localhost:11434/api/generate"

SYSTEM_PROMPT = """You are a knowledgeable fitness assistant creating a workout plan.

Build the plan using ONLY the exercises listed in the context below.
Do not invent exercises, sets, or reps that aren't in the list --
use the default_scheme given for each exercise, adjusting slightly
only if needed to fit the session length.

User profile:
- Goal: {goal}
- Fitness level: {level}
- Days per week: {days}
- Session length: {session_length} minutes
- Equipment available: {equipment}
- Notes from user: {notes}

Safety rule: if the user's notes mention any pain, injury, or medical
condition, do NOT prescribe around it or give medical advice. Instead,
clearly recommend they consult a doctor or physical therapist before
starting, and keep the plan general.

Structure your response as:
1. A brief (1-2 sentence) summary of the plan's focus
2. A day-by-day breakdown (Day 1, Day 2, ...) using only the exercises below,
   with sets/reps for each
3. A short reminder to warm up before and stretch after each session

Available exercises:
{exercise_list}
"""

ALL_EQUIPMENT = [
    "bodyweight", "dumbbells", "barbell", "bench", "squat rack",
    "resistance band", "pull-up bar", "kettlebell", "jump rope", "treadmill",
]

CATEGORY_ICONS = {"strength": "💪", "cardio": "❤️", "core": "🎯", "flexibility": "🧘"}
DIFFICULTY_ORDER = {"beginner": 0, "intermediate": 1, "advanced": 2}


def format_exercise_list(exercises):
    if not exercises:
        return "(no matching exercises found for this equipment/level combination)"
    return "\n".join(
        f"- {e['name']} | {e['muscle_group']} | {e['category']} | {e['difficulty']} | {e['default_scheme']}"
        for e in exercises
    )


def exercises_to_dataframe(exercises):
    """Turns the raw exercise dicts into a clean, readable table --
    formatted equipment, title-cased fields, sorted by muscle group --
    instead of dumping raw Python objects into st.table."""
    rows = []
    for e in sorted(exercises, key=lambda x: (x["muscle_group"], DIFFICULTY_ORDER.get(x["difficulty"], 0))):
        icon = CATEGORY_ICONS.get(e["category"], "")
        rows.append({
            "Exercise": e["name"],
            "Muscle Group": e["muscle_group"].title(),
            "Type": f"{icon} {e['category'].title()}",
            "Level": e["difficulty"].title(),
            "Sets / Reps": e["default_scheme"],
        })
    return pd.DataFrame(rows)


def stream_ollama(prompt, model, placeholder):
    """Streams tokens from Ollama and updates a Streamlit placeholder
    live, so the plan appears word by word instead of all at once."""
    placeholder.markdown("_Thinking..._")
    response = requests.post(
        OLLAMA_URL,
        json={"model": model, "prompt": prompt, "stream": True},
        stream=True,
    )
    response.raise_for_status()

    full_text = ""
    for line in response.iter_lines():
        if not line:
            continue
        chunk = json.loads(line)
        full_text += chunk.get("response", "")
        if full_text:
            placeholder.markdown(full_text)
        if chunk.get("done"):
            break
    return full_text


@st.cache_resource
def load_retriever():
    return WorkoutRetriever("data/exercises.json")


def main():
    st.set_page_config(page_title="Workout Suggestor", page_icon="🏋️", layout="wide")

    st.markdown(
        """
        <style>
        .block-container { padding-top: 2rem; max-width: 900px; }
        div[data-testid="stMetricValue"] { font-size: 1.4rem; }
        </style>
        """,
        unsafe_allow_html=True,
    )

    st.title("🏋️ Workout Suggestor")
    st.caption("Personalized plans generated by a local LLM (Llama/Gemma via Ollama), "
               "grounded in a real exercise database — not invented on the fly.")

    retriever = load_retriever()

    with st.sidebar:
        st.header("⚙️ Model settings")
        model = st.selectbox(
            "Ollama model",
            ["gemma2:2b", "llama3.2:3b", "mistral", "qwen2.5:7b"],
            index=0,
            help="Must already be pulled: ollama pull <model>",
        )
        st.caption("Requires Ollama running locally (`ollama serve`).")
        st.divider()
        st.caption("Built with a RAG pattern: your requirements filter a real "
                   "exercise database first, then the model organizes the result "
                   "into a plan — it can't invent exercises that aren't listed.")

    with st.container(border=True):
        st.subheader("Your requirements")

        col1, col2 = st.columns(2)
        with col1:
            goal = st.selectbox("Goal", list(GOAL_TO_CATEGORIES.keys()))
            level = st.selectbox("Fitness level", ["beginner", "intermediate", "advanced"])
        with col2:
            days = st.slider("Days per week", 1, 7, 3)
            session_length = st.slider("Session length (minutes)", 15, 90, 45, step=5)

        equipment = st.multiselect(
            "Equipment you have access to",
            ALL_EQUIPMENT,
            default=["bodyweight"],
        )

        notes = st.text_area(
            "Anything else? (injuries, focus areas, preferences — optional)",
            placeholder="e.g. bad knees, want to focus on upper body, only have 20 min some days...",
        )

        generate = st.button("Generate my workout plan", type="primary", use_container_width=True)

    if generate:
        if not equipment:
            st.warning("Select at least one piece of equipment (bodyweight counts!).")
            return

        matched = retriever.filter_exercises(goal=goal, equipment=equipment, level=level)

        st.divider()

        m1, m2, m3 = st.columns(3)
        m1.metric("Matched exercises", len(matched))
        m2.metric("Muscle groups covered", len({e["muscle_group"] for e in matched}) if matched else 0)
        m3.metric("Days planned", days)

        with st.expander(f"📋 View the {len(matched)} matched exercises", expanded=False):
            if matched:
                df = exercises_to_dataframe(matched)
                st.dataframe(
                    df,
                    use_container_width=True,
                    hide_index=True,
                    column_config={
                        "Exercise": st.column_config.TextColumn(width="medium"),
                        "Sets / Reps": st.column_config.TextColumn(width="medium"),
                    },
                )
            else:
                st.info("No exercises matched this equipment/level combination — "
                        "try adding more equipment or a different goal.")

        prompt = SYSTEM_PROMPT.format(
            goal=goal, level=level, days=days, session_length=session_length,
            equipment=", ".join(equipment), notes=notes or "none",
            exercise_list=format_exercise_list(matched),
        )

        st.subheader("📅 Your plan")
        with st.container(border=True):
            placeholder = st.empty()
            try:
                stream_ollama(prompt, model, placeholder)
            except requests.exceptions.ConnectionError:
                st.error(
                    "Couldn't reach Ollama. Make sure it's running (`ollama serve`) "
                    f"and that you've pulled the model (`ollama pull {model}`)."
                )
                return
            except requests.exceptions.HTTPError:
                st.error(
                    f"Model `{model}` isn't available in Ollama yet. Run: "
                    f"`ollama pull {model}`, then try again."
                )
                return

        st.info(
            "⚠️ This is general fitness guidance, not medical advice. Check with a "
            "doctor or physical therapist before starting a new program, especially "
            "if you have an injury or health condition."
        )


if __name__ == "__main__":
    main()
